### PR TITLE
Automatic GC if we drop low. Limits debatable...

### PR DESCRIPTION
**Pull request by srhb**
In response to a large build dying from out-of-disk conditions
https://github.com/NixOS/nixpkgs/issues/49442#issuecomment-435320605

### CODE REVIEW

**Comment by srhb** [comment]
@grahamc ping

**Comment by srhb** [comment]
Re. the limits, the question is really how much speed/load saving is won from doing a small gc. If it's slow and expensive anyway (ie. if the constant cost of doing _any_ size GC is high,) we should increase `max-free` a lot. This should probably receive testing on a cross section of the machine types, but this is a starting point.

**Comment by vcunat** [comment]
My feeling from GC on rotating drives is that vast majority of time is taken by unlinking files.

**Comment by srhb** [comment]
@vcunat That sounds like a small GC is indeed preferable. :)

**Comment by edolstra** [comment]
Seems like a good way to give the auto-GC feature some testing :-)

**Comment by vcunat** [comment]
BTW, on `t2a` I've seen running out of inodes while having plenty of free space (more than half).  I plan to work around that just by collecting everything relatively often (once a day or so), since the machine won't benefit much from caching.  Only the `metrics` job is ran there and that's rather special; it seems unlikely to happen on other machines.

**Comment by zimbatm** [comment]
I want to deploy this soon. It requires some careful manual rolling deployment to avoid breaking all of the nodes.

**Comment by davidak** [comment]
Any update on this?

**Comment by zimbatm** [comment]
I haven't touched the NixOS infra in a long time now. Somebody else should probably take over.

**Pull request closed without merging**
