### PR TITLE
add dns record for vault.nixos.org

### PR DESCRIPTION
**Pull request by JulienMalka**
In preparation for an upcoming PR deploying vaultwarden

### CODE REVIEW

**Comment by mweinelt** [comment]
Why did you choose the plural form?

**Comment by JulienMalka** [comment]
Hmm I don't know, a vaultwarden instance may host several vaults that can be shared with different people in function of the need, but I don't have any strong feeling.

**Comment by zimbatm** [comment]
I can see myself using the singular instead of the plural by mistake. But you get to pick since you're deploying it. It could also be pass.nixos.org, bitwarden.nixos.org or bw.nixos.org.

Let me know :)

**Comment by JulienMalka** [comment]
Changed to `vault.nixos.org`, less confusing :)

**Comment by JulienMalka** [comment]
Thanks

**Pull request merged**
