### PR TITLE
20.03 is EOL

### PR DESCRIPTION
**Pull request by jonringer**
related: https://github.com/NixOS/nixpkgs/issues/101975

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Comment by cole-h** [comment]
Another question that I think should be answered: is this when we want to drop 19.09 from the status page altogether?

**Comment by jonringer** [comment]
> Another question that I think should be answered: is this when we want to drop 19.09 from the status page altogether?

I'm not confident in what is consuming this information, or in what ways. If someone from infra says yes, then I'll be happy to remove the 19.09 entries altogether.

**Comment by vcunat** [comment]
Still not shown on https://status.nixos.org/  Some re-deploy step is missing?

**Comment by jonringer** [comment]
I'm assuming the homepage needs to update the flakes

cc @garbas

**Comment by garbas** [comment]
@edolstra when you merged this did you deployed to eris? channels.nix are being served by prometheus which is on eris (i think).

**Pull request merged**
