### PR TITLE
channels: 21.11 is stable, 21.05 is deprecated

### PR DESCRIPTION
**Pull request by cole-h**

### CODE REVIEW

**Comment by vcunat** [comment]
Needs redeploy? :-) I *still* can't see 21.05 as EOL on https://status.nixos.org

**Comment by vcunat** [comment]
Wait, "deprecated" now when the previous use "unmaintained"?

**Comment by vcunat** [comment]
Oh, I suspect we just need to transition them from "deprecated" to "unmaintained" now.

**Comment by cole-h** [comment]
Yep, indeed -- December 2021 is over, so we can mark 21.05 as unmaintained now :)

https://github.com/NixOS/nixpkgs/blob/67cc0b103ab45ca2babb97d96e26d50dd0061644/nixos/doc/manual/release-notes/rl-2105.section.md?plain=1#L3

**Comment by vcunat** [comment]
https://github.com/NixOS/nixos-org-configurations/pull/201

**Pull request merged**
