### PR TITLE
umbriel: init

### PR DESCRIPTION
**Pull request by mweinelt**
This is an ARM64 VM at Hetzner Cloud, that we plan to use for the Matrix moderation bot Mjölnir.

### CODE REVIEW

**Comment by mweinelt** [comment]
Machine is live, nixos-anywhere did the trick.

**Comment by mweinelt** [comment]
@zimbatm would love a tf rollout for DNS when you have the chance.

**Review by JulienMalka — APPROVED** [review]
Thanks you !

**Comment by delroth** [comment]
> @zimbatm would love a tf rollout for DNS when you have the chance.

I took care of it.

```
$ host umbriel.nixos.org
umbriel.nixos.org has address 37.27.20.162
umbriel.nixos.org has IPv6 address 2a01:4f9:c011:8fb5::1
```

**Pull request merged**
