### PR TITLE
webserver.nix: update to reflect changes in httpd module options

### PR DESCRIPTION
**Pull request by aanderse**
Depends on https://github.com/NixOS/nixpkgs/pull/73113.

### CODE REVIEW

**Comment by aanderse** [comment]
ping @edolstra @grahamc @zimbatm

**Comment by edolstra** [comment]
Does this depend on NixOS 20.03 or can it be merged now?

**Comment by aanderse** [comment]
@edolstra definitely requires 20.03!

**Comment by davidak** [comment]
nixos.org is now served by netlify, so can this code be removed completely?

**Comment by aanderse** [comment]
Right! I forgot to close this. Thanks.

**Pull request closed without merging**
