### PR TITLE
rhea: add a backup arm64 bid

### PR DESCRIPTION
**Pull request by cole-h**

### CODE REVIEW

**Review by vcunat — CHANGES_REQUESTED** [review]
```
Error: unknown variant `backup`, expected `small` or `bigparallel` at line 4 column 14
Location:
    src/hardware.rs:54:26
```

**Comment by cole-h** [comment]
Damn.

**Comment by cole-h** [comment]
@vcunat Could you try again from the latest tip of this branch?

(Drafted because I'll merge https://github.com/DeterminateSystems/hydra-scale-equinix-metal/pull/4 if it works and then update the lockfile accordingly before this PR should be merged)

**Comment by vcunat** [comment]
```
error: package `clap_builder v4.4.4` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.1
```

**Comment by cole-h** [comment]
Ideal. I'll undo the Crate.lock update. Try again? (Sorry...)

**Comment by vcunat** [comment]
No problem
```
systemd[1]: Started hydra-scale-equinix-metal.service.                                                                                              
scale[3948102]: Work summary:                                                                                                                       
scale[3948102]: System("x86_64-linux") Small = 2607                                                                                                 
scale[3948102]: System("x86_64-linux") BigParallel = 2                                                                                              
scale[3948102]: System("aarch64-linux") Small = 42343                                                                                               
scale[3948102]: System("aarch64-linux") BigParallel = 57                                                                                            
scale[3948102]: Creating: HardwarePlan {                                                                                                            
scale[3948102]:     bid: 2.0,                                                                                                                       
scale[3948102]:     plan: "c3.large.arm64",                                                                                                         
scale[3948102]:     netboot_url: "https://netboot.nixos.org/dispatch/hydra/hydra.nixos.org/equinix-metal-builders/main/c3-large-arm--big-parallel", 
scale[3948102]: }                                                                                                                                   
scale[3948102]: Error: failed to parse json, here's the raw content: Object {                                                                       
scale[3948102]:     "errors": Array [                                                                                                               
scale[3948102]:         String("There aren't available servers at any facility"),                                                                   
scale[3948102]:     ],                                                                                                                              
scale[3948102]: }                                                                                                                                   
scale[3948102]: Caused by:                                                                                                                          
scale[3948102]:     missing field `hostname` at line 1 column 61                                                                                    
scale[3948102]: Location:                                                                                                                           
scale[3948102]:     src/device.rs:92:10                                                                                                             
systemd[1]: hydra-scale-equinix-metal.service: Main process exited, code=exited, status=1/FAILURE                                                   
```

**Comment by vcunat** [comment]
🤦🏽 
> String("Spot price max can't be greater than 2.0."),

**Comment by cole-h** [comment]
Damn x2.

**Pull request closed without merging**
