### PR TITLE
terraform: enable segment caching for NAR files

### PR DESCRIPTION
**Pull request by zimbatm**
This should fix the issue we're seeing in #207

### CODE REVIEW

**Comment by vcunat** [comment]
The docs look good to me: https://docs.fastly.com/en/guides/segmented-caching

**Comment by zimbatm** [comment]
> HTTP chunked transfer encoding between Fastly and origin isn't supported. Your origin server must frame responses to Range: requests with the Content-Length heade

that's my only concern, but I think S3 behaves properly

**Comment by vcunat** [comment]
Right, in this part I only hoped; I don't know such HTTP details.

**Comment by vcunat** [comment]
Yeah, maybe `.nar.xz` is parsed as just `.xs` extension?

**Comment by zimbatm** [comment]
okay, using the path matching works, and is more future-proof

**Pull request merged**
