### PR TITLE
channels: 23.05 is unmaintained

### PR DESCRIPTION
**Pull request by figsoda**
EOL was on 2023-12-31

Happy new year!

### CODE REVIEW

**Comment by mweinelt** [comment]
Still needs someone to deploy.

**Comment by vcunat** [comment]
Deployed eris.  Visible at https://status.nixos.org

**Comment by vcunat** [comment]
_Subscribing to a repo won't make this PR show in /notifications?_

**Comment by mweinelt** [comment]
Only if  you watch all activity.

> Deployed eris. Visible at [status.nixos.org](https://status.nixos.org/)

Thanks. I wonder, didn't you remove NixOS 22.11 recently, because the page became to long? Now it is back.

**Pull request merged**
