### PR TITLE
channels: Mark 22.05 unmaintained

### PR DESCRIPTION
**Pull request by mweinelt**
EOL was on 2022-12-31.

### CODE REVIEW

**Comment by vcunat** [comment]
Maybe also drop 20.09 completely?

**Comment by mweinelt** [comment]
Fine with me. What about 21.05 and 21.11?

**Comment by vcunat** [comment]
Not sure.  Last updated 5 months ago so perhaps effectively dead anyway.

**Comment by vcunat** [comment]
Missing deploy to `bastion`?  I still can't see any difference on https://status.nixos.org/

**Pull request merged**
