### PR TITLE
terraform/fastlylog: add my own S3 bucket

### PR DESCRIPTION
**Pull request by RaitoBezarius**
I would like to request access to the S3 logs as I would like to conduct work to expose open data to the NixOS community regarding the access pattern to our Fastly CDN, this is performed in the context of bringing our own self hosted binary cache.

But also as part of more long term work to offer self-service data to our community so they can work on popcount, and more.

I am not expert enough in Terraform to write stuff that works on the first try without being able to `terraform init`, so I'd love to get help from admin folks here.

I am also open to reduce the scope of the data I receive, I was planning to postprocess them anyway to do proper aggregation to keep interesting data but not expose any PII data, obviously.

If that's not okay, let me know what we can do to aim for this purpose.

cc @lheckemann @ninjatrappeur

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
I provided the secret key to @zimbatm.

**Comment by RaitoBezarius** [comment]
> Wouldn't it be more useful to get access to the Athena database that gets produced from the fastly logs? (See [`master`/metrics/fastly](https://github.com/NixOS/nixos-org-configurations/tree/master/metrics/fastly?rgh-link-date=2023-08-23T13%3A01%3A12Z))

That would be definitely awesome, how to organize the access to it?

**Comment by edolstra** [comment]
CC @zimbatm who is working on our AWS account management.

**Comment by zimbatm** [comment]
fixed by #286

**Pull request closed without merging**
